version: "3.8"

services:
  backend:
    build:
      context: ./api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: mongo
    ports:
      - "27017:27017"
