name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Backend steps
      - name: Install Backend Dependencies
        run: npm ci
        working-directory: ./api

      - name: Run Backend Tests
        run: npm test
        working-directory: ./api

      # Frontend steps
      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Run Frontend Tests
        run: npm run test
        working-directory: ./frontend
